name: Build and deploy Node.js app to Azure Web App - ragprwebapps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_GITHUB_ID: ${{ secrets.NEXT_PUBLIC_GITHUB_ID }}
          NEXT_PUBLIC_GITHUB_SECRET: ${{ secrets.NEXT_PUBLIC_GITHUB_SECRET }}
          NEXT_PUBLIC_AUTH_SECRET: ${{ secrets.NEXT_PUBLIC_AUTH_SECRET }}
        run: |
          cd fe
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Copy artifact for deployment job
        run: |
          cd fe
          mkdir deploy
          cp -r ./.next/standalone/. ./deploy
          cp -r ./public ./deploy
          cp -r ./.next/static/. ./deploy/.next/static

      - name: Zip artifact for deployment
        run: |
          cd fe/deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: fe/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy
      
      - name: Verify server.js
        run: |
          if [ ! -f "./deploy/server.js" ]; then
            echo "Error: server.js not found in deploy directory"
            exit 1
          fi
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_34C27BA2C75C400A9197E9748AC489ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A61BDE09819545E8B5599C0D70B8D4F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B459E9BB264648D5A67410637A8C0727 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ragprwebapps'
          slot-name: 'Production'
          package: ./deploy
